apiVersion: apps/v1
kind: Deployment
metadata:
  name: taskit-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: taskit
  template:
    metadata:
      labels:
        app: taskit
    spec:
      containers:
      - name: taskit
        image: sktasktracker.azurecr.io/taskit-app:v1
        imagePullPolicy: Always
        ports:
        - containerPort: 8501
